/**
 * Persistence for JP dated-catalysts generated by AA (agentId 55560).
 *
 * Keyed by seed_key (deterministic from config) so a record exists and can be
 * refreshed/polled even before it is submitted to osd (submit is gated on osd
 * JP support). Reuses the existing Upstash REST pattern with a local-JSON
 * fallback, matching the other AA stores.
 *
 *   osd_jp_catalyst:{seed_key}  → JSON JpCatalystRecord
 *   osd_jp_catalysts_index      → SET of seed_keys
 */
import * as fs from "fs";
import * as path from "path";
import { upstashConfigured, upstashCommand } from "../store/upstash-rest";
import type { JpCatalystRecord } from "./types";

const FILE_PATH = path.join(process.cwd(), "data", "osd", "jp-catalysts.json");
const recKey = (seedKey: string): string => `osd_jp_catalyst:${seedKey}`;
const INDEX = "osd_jp_catalysts_index";

interface FileShape {
  catalysts: JpCatalystRecord[];
}

function loadFile(): FileShape {
  try {
    return JSON.parse(fs.readFileSync(FILE_PATH, "utf-8")) as FileShape;
  } catch {
    return { catalysts: [] };
  }
}

function saveFile(data: FileShape): void {
  fs.mkdirSync(path.dirname(FILE_PATH), { recursive: true });
  fs.writeFileSync(FILE_PATH, JSON.stringify(data, null, 2), "utf-8");
}

export async function getJpCatalyst(seedKey: string): Promise<JpCatalystRecord | undefined> {
  if (upstashConfigured()) {
    const raw = await upstashCommand<string | null>(["GET", recKey(seedKey)]);
    return raw ? (JSON.parse(raw) as JpCatalystRecord) : undefined;
  }
  return loadFile().catalysts.find((c) => c.seed_key === seedKey);
}

export async function saveJpCatalyst(rec: JpCatalystRecord): Promise<void> {
  if (upstashConfigured()) {
    await upstashCommand(["SET", recKey(rec.seed_key), JSON.stringify(rec)]);
    await upstashCommand(["SADD", INDEX, rec.seed_key]);
    return;
  }
  const data = loadFile();
  const idx = data.catalysts.findIndex((c) => c.seed_key === rec.seed_key);
  if (idx >= 0) data.catalysts[idx] = rec;
  else data.catalysts.push(rec);
  saveFile(data);
}

export async function listJpCatalysts(): Promise<JpCatalystRecord[]> {
  if (upstashConfigured()) {
    const keys = (await upstashCommand<string[] | null>(["SMEMBERS", INDEX])) ?? [];
    const out: JpCatalystRecord[] = [];
    for (const k of keys) {
      const raw = await upstashCommand<string | null>(["GET", recKey(k)]);
      if (raw) out.push(JSON.parse(raw) as JpCatalystRecord);
    }
    return out;
  }
  return loadFile().catalysts;
}
